/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description The user's alerts, newest first.
         */
        get: operations["list_alerts_api_v1_alerts__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Now
         * @description Evaluate this user's watchlist immediately.
         *
         *     The periodic task covers everyone on a schedule; this exists so a user does
         *     not have to wait for the next sweep after setting a target.
         */
        post: operations["check_now_api_v1_alerts_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark All Read
         * @description Clear the unread badge in one call.
         */
        post: operations["mark_all_read_api_v1_alerts_read_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Read
         * @description Mark one alert as read.
         */
        post: operations["mark_read_api_v1_alerts__alert_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List User Jobs
         * @description List all analysis jobs for the current user.
         */
        get: operations["list_user_jobs_api_v1_analysis__get"];
        put?: never;
        /**
         * Start Analysis
         * @description Start a new stock analysis job for the given ticker.
         *
         *     A recent completed analysis of the same ticker is returned as-is unless
         *     `force` is set: the underlying filings are quarterly, so re-running minutes
         *     later spends eleven provider requests and one of the user's daily analyses
         *     to rebuild the same report. Free-tier users are limited to a daily cap.
         */
        post: operations["start_analysis_api_v1_analysis__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Status
         * @description Get the current status of an analysis job.
         */
        get: operations["get_job_status_api_v1_analysis__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Send a password reset link. Always returns 200 to prevent email enumeration.
         */
        post: operations["forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate a user and return access + refresh tokens.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Current User
         * @description Return the currently authenticated user's profile.
         */
        get: operations["read_current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Exchange a valid refresh token for a new access + refresh token pair.
         */
        post: operations["refresh_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user account and send a verification email.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend Verification
         * @description Resend the email verification link.
         */
        post: operations["resend_verification_api_v1_auth_resend_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Reset a user's password using a signed token.
         */
        post: operations["reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Email
         * @description Verify a user's email with a signed token.
         */
        post: operations["verify_email_api_v1_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chart/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chart Data
         * @description Return historical OHLCV data + computed technical indicators for a ticker.
         */
        get: operations["get_chart_data_api_v1_chart__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compare/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Stocks
         * @description Compare two stocks side-by-side across valuation, profitability, growth, and health.
         */
        get: operations["compare_stocks_api_v1_compare__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/quote-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Batch Quotes
         * @description Return quotes for several tickers.
         *
         *     FMP's own batch-quote endpoint is not available on the current plan — it
         *     answers every request with "Restricted Endpoint", so this used to fail
         *     100% of the time. Single quotes are issued concurrently instead, and the
         *     per-symbol cache means a repeated watchlist refresh mostly costs nothing.
         */
        get: operations["get_batch_quotes_api_v1_dashboard_quote_batch_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/quote/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quick Quote
         * @description Return a quote for a single ticker.
         */
        get: operations["get_quick_quote_api_v1_dashboard_quote__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Ticker
         * @description Search for stock tickers or companies by name or symbol.
         */
        get: operations["search_ticker_api_v1_dashboard_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Stats
         * @description Aggregated stats for the authenticated user's dashboard.
         */
        get: operations["get_dashboard_stats_api_v1_dashboard_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Call Performance
         * @description How the user's past recommendations have fared against the market since.
         *
         *     This is deliberately descriptive rather than a claim of skill: a handful of
         *     calls over a few weeks says almost nothing, so the response carries the
         *     sample size and the window alongside the numbers.
         */
        get: operations["call_performance_api_v1_history__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Leaderboard
         * @description The user's analysed tickers ranked by composite score.
         *
         *     Screening the whole market by our own factor model would mean running the
         *     pipeline per candidate, which the provider quota does not allow. Ranking
         *     what has already been analysed gives the same view of "where does this sit
         *     against everything else I have looked at" for no extra requests.
         */
        get: operations["leaderboard_api_v1_history_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ticker History
         * @description Every analysis this user has run on a ticker, oldest first, with the change
         *     since the previous run.
         */
        get: operations["ticker_history_api_v1_history__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/gainers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top Gainers */
        get: operations["top_gainers_api_v1_market_gainers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock Lists
         * @description Return all available curated stock lists with metadata.
         */
        get: operations["get_stock_lists_api_v1_market_lists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/lists/{list_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock List Detail
         * @description Return a curated stock list with live quotes for each ticker.
         */
        get: operations["get_stock_list_detail_api_v1_market_lists__list_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/losers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top Losers */
        get: operations["top_losers_api_v1_market_losers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/most-active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Most Active */
        get: operations["most_active_api_v1_market_most_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/sector-performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sector Performance */
        get: operations["sector_performance_api_v1_market_sector_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description Retrieve a report by its ID. Only the report owner can access it.
         */
        get: operations["get_report_api_v1_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screener/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Screen Stocks
         * @description Screen stocks using FMP's screener API with various filters.
         *     Returns a list of matching stocks with key metrics.
         */
        get: operations["screen_stocks_api_v1_screener__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screener/exchanges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Exchanges
         * @description Return available exchanges for the screener filter.
         */
        get: operations["list_exchanges_api_v1_screener_exchanges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screener/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sectors
         * @description Return available sectors for the screener filter.
         */
        get: operations["list_sectors_api_v1_screener_sectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stripe/cancel-subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Subscription
         * @description Cancel the current user's Stripe subscription.
         */
        post: operations["cancel_subscription_api_v1_stripe_cancel_subscription_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stripe/create-checkout-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Checkout Session
         * @description Create a Stripe checkout session for the premium subscription.
         */
        post: operations["create_checkout_session_api_v1_stripe_create_checkout_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stripe/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe Webhook
         * @description Handle incoming Stripe webhook events.
         */
        post: operations["stripe_webhook_api_v1_stripe_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Watchlist
         * @description Return the current user's watchlist.
         */
        get: operations["list_watchlist_api_v1_watchlist__get"];
        put?: never;
        /**
         * Add Watchlist Item
         * @description Add a ticker to the user's watchlist.
         */
        post: operations["add_watchlist_item_api_v1_watchlist__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Watchlist Item
         * @description Remove a ticker from the user's watchlist.
         */
        delete: operations["remove_watchlist_item_api_v1_watchlist__item_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Watchlist Item
         * @description Update notes or the price target on a watchlist item.
         */
        patch: operations["update_watchlist_item_api_v1_watchlist__item_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisJob */
        AnalysisJob: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Message */
            error_message?: string | null;
            /** Id */
            id: number;
            /** Report Id */
            report_id?: number | null;
            /** Status */
            status: string;
            /** Ticker */
            ticker: string;
            /** User Id */
            user_id: number;
        };
        /** AnalysisJobCreate */
        AnalysisJobCreate: {
            /** Ticker */
            ticker: string;
        };
        /** BarDataPoint */
        BarDataPoint: {
            /** Name */
            name: string;
            /** Value */
            value: number | null;
        };
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /** BollingerBands */
        BollingerBands: {
            /** Lower */
            lower: number | null;
            /** Middle */
            middle: number | null;
            /** Upper */
            upper: number | null;
        };
        /**
         * ChartData
         * @description Everything the report page's charts read. See module docstring.
         */
        ChartData: {
            /** Atr */
            atr: number | null;
            bollinger_bands: components["schemas"]["BollingerBands"];
            /**
             * Company Name
             * @default Unknown
             */
            company_name: string;
            /** Current Price */
            current_price: number | null;
            dcf: components["schemas"]["DcfSummary"];
            /** Dividend History */
            dividend_history: components["schemas"]["DividendPoint"][];
            earnings: components["schemas"]["EarningsSummary"];
            /** Growth */
            growth: components["schemas"]["BarDataPoint"][];
            /** Leverage */
            leverage: {
                [key: string]: number | null;
            };
            /** Liquidity */
            liquidity: {
                [key: string]: number | null;
            };
            macd: components["schemas"]["Macd"];
            momentum: components["schemas"]["Momentum"];
            moving_averages: components["schemas"]["MovingAverages"];
            peers: components["schemas"]["PeersSummary"];
            /** Price Series */
            price_series: components["schemas"]["PricePoint"][];
            /** Profitability */
            profitability: components["schemas"]["BarDataPoint"][];
            recommendation: components["schemas"]["RecommendationSummary"];
            revenue_segments: components["schemas"]["RevenueSegments"] | null;
            risk: components["schemas"]["RiskSummary"];
            /** Rsi */
            rsi: number | null;
            /** Sentiment */
            sentiment: components["schemas"]["SentimentSlice"][];
            /**
             * Sentiment Score
             * @default 0
             */
            sentiment_score: number;
            support_resistance: components["schemas"]["SupportResistance"];
            /**
             * Ticker
             * @default
             */
            ticker: string;
            /** Trend Signals */
            trend_signals: string[];
            /** Valuation Multiples */
            valuation_multiples: components["schemas"]["BarDataPoint"][];
            volume_profile: components["schemas"]["VolumeProfile"];
        };
        /** DcfSummary */
        DcfSummary: {
            /** Current Price */
            current_price: number | null;
            /** Error */
            error: string | null;
            /** Intrinsic Value */
            intrinsic_value: number | null;
            /** Net Debt */
            net_debt: number | null;
            /** Status */
            status: string | null;
            /** Value High */
            value_high: number | null;
            /** Value Low */
            value_low: number | null;
            /** Wacc */
            wacc: number | null;
        };
        /** DividendPoint */
        DividendPoint: {
            /** Date */
            date: string;
            /** Dividend */
            dividend: number;
        };
        /** EarningsSummary */
        EarningsSummary: {
            /**
             * Available
             * @default false
             */
            available: boolean;
            /** Beat Rate */
            beat_rate: number | null;
            /** Days Until */
            days_until: number | null;
            /** Eps Estimate */
            eps_estimate: number | null;
            /** Is Imminent */
            is_imminent: boolean | null;
            /** Next Date */
            next_date: string | null;
            /** Note */
            note: string | null;
            /** Recent Surprises */
            recent_surprises: components["schemas"]["EarningsSurprise"][];
            /** Reports Assessed */
            reports_assessed: number | null;
        };
        /** EarningsSurprise */
        EarningsSurprise: {
            /** Date */
            date: string | null;
            /** Eps Actual */
            eps_actual: number | null;
            /** Eps Estimated */
            eps_estimated: number | null;
            /** Surprise Pct */
            surprise_pct: number | null;
        };
        /** EmailVerifyRequest */
        EmailVerifyRequest: {
            /** Token */
            token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Macd */
        Macd: {
            /** Macd Histogram */
            macd_histogram: number | null;
            /** Macd Line */
            macd_line: number | null;
            /** Signal Line */
            signal_line: number | null;
        };
        /** Momentum */
        Momentum: {
            /** Price Momentum 1M */
            price_momentum_1m: number | null;
            /** Price Momentum 3M */
            price_momentum_3m: number | null;
            /** Price Momentum 6M */
            price_momentum_6m: number | null;
        };
        /** MovingAverages */
        MovingAverages: {
            /** Sma 20 */
            sma_20: number | null;
            /** Sma 200 */
            sma_200: number | null;
            /** Sma 50 */
            sma_50: number | null;
        };
        /** PasswordResetConfirm */
        PasswordResetConfirm: {
            /** New Password */
            new_password: string;
            /** Token */
            token: string;
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** PeerCompany */
        PeerCompany: {
            /** Market Cap */
            market_cap: number | null;
            /** Name */
            name: string | null;
            /** Symbol */
            symbol: string | null;
        };
        /**
         * PeerMetricComparison
         * @description One metric measured against the peer group.
         *
         *     `premium_discount` is the company's position relative to the peer median, so
         *     negative means cheaper for a multiple and weaker for a margin — read it with
         *     `lower_is_better`.
         */
        PeerMetricComparison: {
            /** Company */
            company: number | null;
            /** Key */
            key: string | null;
            /** Label */
            label: string | null;
            /** Lower Is Better */
            lower_is_better: boolean | null;
            /** Peer Median */
            peer_median: number | null;
            /** Percentile */
            percentile: number | null;
            /** Premium Discount */
            premium_discount: number | null;
            /** Verdict */
            verdict: string | null;
        };
        /** PeersSummary */
        PeersSummary: {
            /** Companies */
            companies: components["schemas"]["PeerCompany"][];
            /** Comparisons */
            comparisons: components["schemas"]["PeerMetricComparison"][];
            /**
             * Peer Count
             * @default 0
             */
            peer_count: number;
            /** Relative Valuation Score */
            relative_valuation_score: number | null;
            sector: components["schemas"]["SectorSnapshot"];
            /** Summary */
            summary: string | null;
        };
        /** PricePoint */
        PricePoint: {
            /** Close */
            close: number | null;
            /** Date */
            date: string | null;
            /** High */
            high: number | null;
            /** Low */
            low: number | null;
            /** Volume */
            volume: number | null;
        };
        /**
         * RecommendationFactor
         * @description One scored dimension of the recommendation. `score` is null when the
         *     factor had insufficient data.
         */
        RecommendationFactor: {
            /** Drivers */
            drivers: string[];
            /** Key */
            key: string | null;
            /** Label */
            label: string | null;
            /** Score */
            score: number | null;
            /** Weight */
            weight: number | null;
        };
        /** RecommendationSummary */
        RecommendationSummary: {
            /** Call */
            call: string | null;
            /** Composite Score */
            composite_score: number | null;
            /** Confidence */
            confidence: number | null;
            /** Coverage */
            coverage: number | null;
            /** Factors */
            factors: components["schemas"]["RecommendationFactor"][];
            /** Rationale */
            rationale: string | null;
        };
        /** RefreshTokenRequest */
        RefreshTokenRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** Report */
        Report: {
            chart_data?: components["schemas"]["ChartData"] | null;
            /** Content */
            content?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Job Id */
            job_id: number;
        };
        /** RevenueSegment */
        RevenueSegment: {
            /** Name */
            name: string;
            /** Value */
            value: number;
        };
        /** RevenueSegments */
        RevenueSegments: {
            /** Geographic */
            geographic: components["schemas"]["RevenueSegment"][];
            /** Product */
            product: components["schemas"]["RevenueSegment"][];
        };
        /** RiskSummary */
        RiskSummary: {
            /** Annual Volatility */
            annual_volatility: number | null;
            /** Annualized Return */
            annualized_return: number | null;
            /** Beta */
            beta: number | null;
            /** Max Drawdown Pct */
            max_drawdown_pct: number | null;
            /**
             * Rating
             * @default unknown
             */
            rating: string;
            /** Sharpe Ratio */
            sharpe_ratio: number | null;
            /** Sortino Ratio */
            sortino_ratio: number | null;
            /** Var 95 */
            var_95: number | null;
            /** Window End */
            window_end: string | null;
            /** Window Start */
            window_start: string | null;
        };
        /** SectorSnapshot */
        SectorSnapshot: {
            /** As Of */
            as_of: string | null;
            /** Industry */
            industry: string | null;
            /** Industry Pe */
            industry_pe: number | null;
            /** Sector */
            sector: string | null;
            /** Sector Pe */
            sector_pe: number | null;
            /** Vs Industry Pe */
            vs_industry_pe: number | null;
            /** Vs Sector Pe */
            vs_sector_pe: number | null;
        };
        /** SentimentSlice */
        SentimentSlice: {
            /** Color */
            color: string | null;
            /** Name */
            name: string;
            /**
             * Value
             * @default 0
             */
            value: number;
        };
        /** SupportResistance */
        SupportResistance: {
            /** Resistance */
            resistance: number | null;
            /** Support */
            support: number | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** User */
        User: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Id */
            id: number;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
            /** Subscription Status */
            subscription_status: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VolumeProfile */
        VolumeProfile: {
            /** Avg Volume */
            avg_volume: number | null;
            /** Relative Volume */
            relative_volume: number | null;
        };
        /** WatchlistItem */
        WatchlistItem: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Notes */
            notes?: string | null;
            /** Target Direction */
            target_direction?: string | null;
            /** Target Price */
            target_price?: number | null;
            /** Ticker */
            ticker: string;
            /** User Id */
            user_id: number;
        };
        /** WatchlistItemCreate */
        WatchlistItemCreate: {
            /** Notes */
            notes?: string | null;
            /** Target Direction */
            target_direction?: string | null;
            /** Target Price */
            target_price?: number | null;
            /** Ticker */
            ticker: string;
        };
        /** WatchlistItemUpdate */
        WatchlistItemUpdate: {
            /** Notes */
            notes?: string | null;
            /** Target Direction */
            target_direction?: string | null;
            /** Target Price */
            target_price?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_alerts_api_v1_alerts__get: {
        parameters: {
            query?: {
                unread_only?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_now_api_v1_alerts_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    mark_all_read_api_v1_alerts_read_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    mark_read_api_v1_alerts__alert_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_user_jobs_api_v1_analysis__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJob"][];
                };
            };
        };
    };
    start_analysis_api_v1_analysis__post: {
        parameters: {
            query?: {
                /** @description Re-run even if a recent analysis of this ticker exists */
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_status_api_v1_analysis__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_api_v1_auth_resend_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_api_v1_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chart_data_api_v1_chart__ticker__get: {
        parameters: {
            query?: {
                /** @description 1m, 3m, 6m, 1y, 2y, 5y, max */
                timeframe?: string;
                /** @description Comma-separated: sma,ema,rsi,macd,bollinger */
                indicators?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_stocks_api_v1_compare__get: {
        parameters: {
            query: {
                /** @description First ticker symbol */
                ticker1: string;
                /** @description Second ticker symbol */
                ticker2: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_quotes_api_v1_dashboard_quote_batch_get: {
        parameters: {
            query: {
                /** @description Comma-separated ticker symbols */
                symbols: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quick_quote_api_v1_dashboard_quote__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_ticker_api_v1_dashboard_search_get: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_stats_api_v1_dashboard_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    call_performance_api_v1_history__get: {
        parameters: {
            query?: {
                /** @description Ignore calls younger than this, which have not played out */
                min_age_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leaderboard_api_v1_history_leaderboard_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ticker_history_api_v1_history__ticker__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    top_gainers_api_v1_market_gainers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_stock_lists_api_v1_market_lists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_stock_list_detail_api_v1_market_lists__list_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                list_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    top_losers_api_v1_market_losers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    most_active_api_v1_market_most_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sector_performance_api_v1_market_sector_performance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_report_api_v1_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    screen_stocks_api_v1_screener__get: {
        parameters: {
            query?: {
                /** @description Sector filter (e.g. Technology, Healthcare) */
                sector?: string | null;
                /** @description Industry filter */
                industry?: string | null;
                /** @description Minimum market cap */
                marketCapMin?: number | null;
                /** @description Maximum market cap */
                marketCapMax?: number | null;
                /** @description Minimum price */
                priceMin?: number | null;
                /** @description Maximum price */
                priceMax?: number | null;
                /** @description Minimum dividend yield */
                dividendMin?: number | null;
                /** @description Minimum average volume */
                volumeMin?: number | null;
                betaMin?: number | null;
                betaMax?: number | null;
                /** @description Country (e.g. US, GB) */
                country?: string | null;
                /** @description Exchange (e.g. NASDAQ, NYSE) */
                exchange?: string | null;
                /** @description Max results */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exchanges_api_v1_screener_exchanges_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_sectors_api_v1_screener_sectors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    cancel_subscription_api_v1_stripe_cancel_subscription_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_checkout_session_api_v1_stripe_create_checkout_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stripe_webhook_api_v1_stripe_webhook_post: {
        parameters: {
            query?: never;
            header?: {
                "stripe-signature"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_api_v1_watchlist__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItem"][];
                };
            };
        };
    };
    add_watchlist_item_api_v1_watchlist__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_watchlist_item_api_v1_watchlist__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_watchlist_item_api_v1_watchlist__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
